# Generated by Django 4.2.10 on 2024-03-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('break_in', models.DateTimeField(blank=True, null=True)),
                ('break_out', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
